server:
  port: 8080 

spring:
  cloud:
    gateway:
      routes:
        - id: protected-api-route
          uri: https://httpbin.org 
          predicates:
            - Path=/api/**

  data:
    redis:
      host: localhost
      port: 6379